### ISSUE TITLE
Importer issues when exporting global variables to UE 4.25 Project

### ISSUE THREAD

**Issue by Macobrolik** [ArticySoftware/ArticyImporterForUnreal#33]
Hi, 
we're getting the following error when trying to compile the code changes upon exporting the articy project to Unreal.

```
Fehler	C1083	Datei (Include) kann nicht ge�ffnet werden: "Customizations/ArticyEditorCustomizationManager.h": No such file or directory	Megacity	I:\MegacityProject\Plugins\ArticyImporter\Source\ArticyEditor\Public\ArticyEditorModule.h	10	
Fehler	C2039	"Add" ist kein Member von "TWeakObjectPtr<UMegacityInstructionsVariables,FWeakObjectPtr>".	Megacity	I:\MegacityProject\Source\Megacity\ArticyGenerated\MegacityExpressoScripts.h	63	
Fehler	C2039	"Add" ist kein Member von "TWeakObjectPtr<UMegacityInstructionsVariables,FWeakObjectPtr>".	Megacity	I:\MegacityProject\Source\Megacity\ArticyGenerated\MegacityExpressoScripts.h	63	

```

This is part of the code it is referring to: ![unknown](https://user-images.githubusercontent.com/3792048/98470920-0df21e80-21e9-11eb-9d61-c7bad8eaa501.png)

Any help would be greatly appreciated.

**Comment by herr-edgy** [comment]
Hello Macobrolik,

this would be more appropriate to send to our support at support@articy.com (just for future reference).
One issue that immediately stands out is that you called one of your global variable sets "Instructions". The class you are showing in that screenshot inherits from UArticyExpressoScripts, which already has an "Instructions" member, which is a map. Therefore the code is trying to call the Add function on the map, but gets confused because of the dynamically generated member which is also called Instructions.

We will probably include this name on our blacklist for GV namespace names inside articy in the future.

The other issue is that the ArticyEditorCustomizationManager.h apparently can not be found for some reason. Can you confirm it's under ArticyImporter/Source/ArticyEditor/Public/Customizations/ArticyEditorCustomizationManager? If it is, this might also be a false alarm caused by the previous compile issues, so please fix this on your end and try again. If the issue persists, let me know.

**Comment by Macobrolik** [comment]
Hello, 

thanks a lot for the quick reply! I'll keep that in mind for the future.
The issues you mentioned seemed to be it. We managed to fix it by renaming that namespace and adding some of the missing files back in (they didn't get captured by perforce for some weird reason).

Thanks again and have a great day.

Best
