### ISSUE TITLE
Articy Importer menu button does not load.

### ISSUE THREAD

**Issue by Zerophase** [ArticySoftware/ArticyImporterForUnreal#36]
I can't find the Articy Importer menu button via the level toolbar in 4.26.1. I'm on Linux. I don't know if that matters. But, my custom projects and ManiacManford does not have that button. Also, the engine can't find the asset for the button.

**Comment by Zerophase** [comment]
Think I fixed it. Just had to add Linux to the white list. I don't know if the rest of the code supports Linux. I will look into it a bit. But, if there's someway of alerting the user to being on an unsupported platform I'd recommend that. As the engine itself, and everything other than the generating buttons still work, without the white list. It would just be a nice usability feature.

**Comment by brwarner** [comment]
Hey there,

Sorry for the long delay. I'm taking over support of the Unreal plugin at Articy now and am going through our backlog of issues. Linux isn't on our supported platform list primarily because we don't have a good Linux setup to do the proper testing and guarantee functionality for our users. I'm glad it's working for you so far. 

I was curious, was it just the menu item that didn't show up before you whitelisted Linux or was it that the entire plugin wasn't loading? My guess is that Unreal wasn't loading the plugin at all. In that case, it'd be hard for us to show a warning if our code wasn't being run. I'm surprised Unreal Marketplace let you install it. I'd figure they'd be the ones showing the warning to you.

In the meantime, I'm going to mark this issue as closed. We may add official Linux support in the future. In the meantime, you'll have to proceed with caution.
